name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pandas
  - numpy
  - Pillow
  - matplotlib
  - pip
  - pip:
      - ipycanvas
      - scikit-learn
      - sympy
      - requests
      - scipy
      - psutil
      - anywidget
      - ipyvue
      - ipytree
      - qutip
      - seaborn
      - plotly
      - bqplot
      - ipympl
      - altair
      - graphviz
