name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-lua
  - xeus-nelson
  - xeus-r
  - xeus-cpp
  - xeus-javascript
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - ipycanvas
