name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pandas
  - numpy
  - Pillow
  - matplotlib
  - scikit-learn
  - sympy
  - plotly
  - bqplot
  - qutip
  - scipy
  - ipycanvas
  - anywidget
  - ipyvue
  - ipytree
  - seaborn
  - ipympl
  - altair
  - pip
  - pip:
      - requests
      
