name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  # Common scientific libraries
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - sympy
  - qutip

  # Visualization libraries
  - matplotlib
  - seaborn
  - plotly
  - bqplot
  - ipympl
  - altair
  - graphviz
  - pillow

  # Interactive/Geospatial visualization
  - ipyleaflet
  - folium
  - bokeh
  - hvplot
  - holoviews

  # Data I/O & manipulation
  - openpyxl
  - xlrd
  - pyarrow
  - fastparquet
  - sqlalchemy
  - requests

  # Statistical / ML extensions
  - statsmodels
  - xgboost
  - lightgbm

  # Utility packages for notebooks
  - tqdm
  - rich
  - psutil
  - anywidget
  - ipycanvas
  - ipyvue
  - ipytree
  - ipycytoscape

  # Optional: code formatting & linting
  - black
  - flake8
  - isort
